CREATE TABLE PROFESOR();
    DNI_PROFESOR VAECHAR2(9),
	NOMBRE VARCHAR2(30),
	APELLIDO1 VARCHAR2(30),
	APELLIDO2 VARCHAR2(30) NULL,
	DIRECCION VARCHAR2(50),
	CUENTA VARCHAR2(26),
	TELEFONO VARCHAR2(9),
    CONSTRAINT pk_profesor PRIMARY KEY(DNI)
);

CREATE TABLE CICLOFORMATIVO();
     CODIGOCICLO NUMBER(3),
	 NOMBRE VARCHAR2(30),
	 TIPO VARCHAR2(20),
	 CONSTRAINT pk_cicloformativo PRIMARY KEY(CODIGOCICLO)
);

CREATE TABLE ASIGNATURA();
   CODIGOASIGNATURA NUMBER(3),
   NOMBRE VARCHAR2(20),
   NUMEROHORAS VARCHAR2(24),
   CODIGOCICLO NUMBER(3),
   DNI_PROFESOR VAECHAR2(9),
   CONSTRAINT pk_asignatura PRIMARY KEY(CODIGOASIGNATURA),
   CONSTRAINT fk_ciclo FOREIGN KEY(CODIGOCICLO) REFERENCES CICLOFORMATIVO(CODIGOCICLO),
   CONSTRAINT fk_profesor FOREIGN KEY(DNI_PROFESOR) REFERENCES PROFESOR(DNI_PROFESOR)
);

CREATE TABLE IDIOMA();
  CODIGOIDIOMA NUMBER(3),
  DESCRIPCION VARCHAR2(30),
  CONSTRAINT pk_idioma PRIMARY KEY(CODIGOIDIOMA)
);
 
 CREATE TABLE IDIOMASPROF();
   CODIGOIDIOMA NUMBER(3),
   DNI_PROFESOR VAECHAR2(9),
   CONSTRAINT pk_idiomasprof PRIMARY KEY(CODIGOIDIOMA,DNI_PROFESOR),
   CONSTRAINT fk_idioma FOREIGN KEY (CODIGOIDIOMA) REFERENCES IDIOMA(CODIGOIDIOMA),
   CONSTRAINT fk_profesor2 FOREIGN KEY(DNI_PROFESOR) REFERENCES PROFESOR(DNI_PROFESOR)
);
 
 CREATE TABLE ALUMNO();
    DNI_ALUMNO VARCHAR2(9),
	NOMBRE VARCHAR2(30),
	APELLIDO1 VARCHAR2(30),
	APELLIDO2 VARCHAR2(30) NULL,
	DIRECCION VARCHAR2(50),
	EMAIL VARCHAR2(26),
	TELEFONO VARCHAR2(9),
	CODIGOIDIOMA NUMBER(3),
    CONSTRAINT pk_alumno PRIMARY KEY(DNI_ALUMNO),
	CONSTRAINT fk_idioma2 FOREIGN KEY(CODIGOIDIOMA) REFERENCES IDIOMA (CODIGOIDIOMA) NULL
);

CREATE TABLE  MATRICULA();
    DNI_ALUMNO VARCHAR2(9),
	CODIGOASIGNATURA NUMBER(3),
   CONSTRAINT pf_matricula PRIMARY KEY(CODIGOIDIOMA,DNI),
   CONSTRAINT fk_alumno2 FOREIGN KEY(DNI_ALUMNO) REFERENCES ALUMNO(DNI_ALUMNO),
   CONSTRAINT fk_asignatura FOREIGN KEY(CODIGOASIGNATURA) REFERENCES ASIGNATURA(CODIGOASIGNATURA)
 );