CREATE TABLE SEDE(
    CODSEDE VARCHAR2(30),
	NOMBRE VARCHAR2(20),
	DIRECCION VARCHAR2(30)
    CONSTRAINT pk_sede PRIMARY KEY(CODSEDE)
);
CREATE TABLE DEPARTAMENTO(
    CODDEPARTAMENTO VARCHAR2(30),
	NOMBRE VARCHAR2(30),
	UBICACION VARCHAR2(30),
	CODSEDE VARCHAR2(30),
	CONSTRAINT pk_departamento PRIMARY KEY(CODDEPARATAMENTO),
	CONSTRAINT pk_codsede PRIMARY KEY(CODSEDE) REFERENCES SEDE,
    CONSTRAINT fk_codsede FOREIGN KEY(CODSEDE) REFERENCES SEDE
);
CREATE TABLE PROGRAMADOR(
    SECUENCIA VARCHAR2(20),
	NOMBRE VARCHAR2(30),
    APELLIDO1 VARCHAR2(30),
    APELLIDO2 VARCHAR2(20) NULL,
	DIRECCION VARCHAR2(30),
	CUENTA VARCHAR2(30),
    TELEFONO NUMBER(9),
    TIPO VARCHAR2(20),
    SECUENCIA_MENTOR VARCHAR2(20),
	CODSEDE VARCHAR2(30),
	CODDEPARTAMENTO VARCHAR2(30),
	CONSTRAINT pk_programador PRIMARY KEY(SECUENCIA),
	CONSTRAINT fk_secuenciamentor FOREIGN KEY(SECUENCIA_MENTOR) REFERENCES PROGRAMADOR (SECUENCIA)
	CONSTRAINT fk_codsede_coddepartamento FOREIGN KEY(CODSEDE, CODDEPARTAMENTO) REFERENCES( CODSEDE,DEPARTAMENTO)
);
CREATE TABLE EQUIPO(
	SECUENCIA VARCHAR2(29),
	CODEQUIPO NUMBER(20),
	DESCRIPCION VARCHAR2(23),
	CODSEDE VARCHAR2(23),
	CODDEPARTAMENTO VARCHAR2(30),
	CONSTRAINT pk_equipo FOREIGN KEY(SECUENCIA),
	CONSTRAINT fk_prog FOREIGN KEY(SECUENCIA,CODEDEPARTAMENTO,CODSEDE) REFERENCES PROGRAMADOR(SECUENCIA,CODDEPARATAMENTO,CODSEDE)
);
CREATE TABLE EQUIPOPROG (
	CODSEDE VARCHAR2 (30),
	CODDEPARTAMENTO VARCHAR2(30),
	SECUENCIA VARCHAR2(29),
	CODEQUIPO NUMBER(20),
	CONSTRAINT pk_equipoprog PRIMARY KEY(SECUENCIA,CODSEDE,CODEQUIPO),
	CONSTRAINT fk_equipoprog2 FOREIGN KEY(
	CONSTRAINT fk_equipoprrog FOREIGN KEY(CODSEDE,SECUENCIA,CODDEPARATAMENTO) REFERENCES PROGRAMADOR (SEDE,EQUIPOPROG)
);
CREATE TABLE PROYECTO (
	FECHAINICIO DATE,
	DESCRIPCION VARCCHAR2(30),
	FECHAFINAL DATE,
	CODEQUIPO NUMBER(20),
	PARTEPROYECTO DATE,
	CONSTRAINT pk_proyecto PRIMARY KEY(FECHAINICIO,CODEQUIPÒ),
	CONSTRAINT fk_proyecto FOREIGN KEY(PARTEPROYECTO) REFERENCES PROYECTO (PROYECTO),
	CONSTRAINT fk_equipo FOREIGN KEY (CODEQUIPO) REFERENCES EQUIPO (EQUIPO)
);	
